trigger:
  - master
  - test/*
  - refs/tags/*
pr:
  - master

stages:

  - stage: Test
    displayName: 'Run Tests'
    jobs:
    - template: azure-pipelines/azure-pipelines-test-template.yml

  - stage: Increment_version
    displayName: 'Increment Version'
    dependsOn: Test
    condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'refs/tags/'))
    jobs:
    - template: azure-pipelines/azure-pipelines-increment-version-template.yml

  - stage: Release_to_Staging
    displayName: 'Release to Staging'
    dependsOn: Increment_version
    pool: sfpool
    condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'refs/tags/employee'))
    jobs:
    - deployment: deploy_to_staging
      environment: 'staging'
      workspace:
        clean: all
      variables:
      - group: sftest
      strategy:
        runOnce:
          deploy:
            steps:
            - download: none
            - checkout: self
            - template: azure-pipelines/azure-pipelines-deploy-to-sandbox-template.yml
              parameters:
                username: cicd@xploremachinez.com
                devhub_alias: devhub