parameters:
  username: cicd@xploremachinez.com
  poolname: sfpool
  devhub_alias: devhub

jobs:
- job: Increament_build_version
  displayName: 'Increament Build Version'
  variables:
  - group: sftest
  pool:
    name: ${{parameters.poolname}}
  workspace:
    clean: all
  steps:

    - task: AzlamSalam.sfpowerscripts.sfpwowerscript-installsfdx-task.sfpwowerscript-installsfdx-task@7
      displayName: 'Install SFDX'

    - task: AzlamSalam.sfpowerscripts.sfpwowerscript-authenticateorg-task.sfpwowerscript-authenticateorg-task@9
      displayName: 'Authenticate  devhub using JWT'
      inputs:
        method: JWT
        jwt_key_file: server.key
        username: ${{parameters.username}}
        alias: ${{parameters.devhub_alias}}
        isdevhub: true
        clientid: $(jwt-client-id)
      
    - task: AzlamSalam.sfpowerscripts.sfpwowerscript-incrementversionnumber-task.sfpwowerscript-incrementversionnumber-task@9
      displayName: 'Increments the BuildNumber version number '
      inputs:
        appendBuildNumber: true
        package: employee
        project_directory: '$(Build.Repository.LocalPath)'


    - task: AzlamSalam.sfpowerscripts.sfpwowerscripts-createunlockedpackage-task.sfpwowerscripts-createunlockedpackage-task@12
      displayName: 'Creates a new version of employee'
      inputs:
        package: employee
        project_directory: '$(Build.Repository.LocalPath)'
        devhub_alias: '${{parameters.devhub_alias}}'
        isDiffCheck: true
        isGitTag: true
        set_build_number: true

    - task: AzlamSalam.sfpowerscripts.sfpowerscripts-postcreatepackage-task.sfpowerscripts-postcreatepackage-task@1
      displayName: 'Post Execution for Create Package Tasks'
      inputs:
        github_connection: 'abhivan-github'